
[temp_lookup_test_e2e_lk]
collection = temp_lookup_test_e2e_lk
external_type = kvstore
fields_list = _key, h, j

[temp_lookup_debug_lk_001]
collection = temp_lookup_debug_lk_001
external_type = kvstore
fields_list = _key, h, j
