[id]
name = query-tester
version = 0.1.0

[ui]
is_visible = 1
label = Query Tester

[launcher]
author = Splunk
description = QueryTester
version = 0.1.0

[package]
check_for_updates = 0
id = QueryTester

[install]
is_configured = 1
build = 1

[triggers]
reload.splunk_create = simple

[themes]
supported = light,dark
