[script://$SPLUNK_HOME/etc/apps/QueryTester/bin/scheduled_runner.py]
disabled = false
interval = 60
sourcetype = query_tester:scheduled_runner
index = _internal
passAuth = admin
python.version = python3
