[script:query_tester]
match   = /data/tester
script  = query_tester.py
scripttype = persist
handler = query_tester.QueryTesterHandler
requireAuthentication = true
output_mode = json
passPayload = true
passHttpHeaders = true
passHttpCookies = true
passSystemAuth = true
python.version = python3

[script:scheduled_tests]
match   = /data/scheduled_tests
script  = scheduled_tests_handler.py
scripttype = persist
handler = scheduled_tests_handler.ScheduledTestsHandler
requireAuthentication = true
output_mode = json
passPayload = true
passHttpHeaders = true
passHttpCookies = true
passSystemAuth = true
python.version = python3

[script:run_history]
match   = /data/test_run_history
script  = run_history_handler.py
scripttype = persist
handler = run_history_handler.RunHistoryHandler
requireAuthentication = true
output_mode = json
passPayload = true
passHttpHeaders = true
passHttpCookies = true
passSystemAuth = true
python.version = python3

[script:saved_tests]
match   = /data/saved_tests
script  = saved_tests_handler.py
scripttype = persist
handler = saved_tests_handler.SavedTestsHandler
requireAuthentication = true
output_mode = json
passPayload = true
passHttpHeaders = true
passHttpCookies = true
passSystemAuth = true
python.version = python3
