[expose:query_tester]
pattern            = data/tester
methods            = get,post
skipCSRFProtection = 1

[expose:query_tester_sub]
pattern            = data/tester/**
methods            = get,post,put,delete
skipCSRFProtection = 1

[expose:scheduled_tests]
pattern            = data/scheduled_tests
methods            = get,post,put,delete
skipCSRFProtection = 1

[expose:run_history]
pattern            = data/test_run_history
methods            = get
skipCSRFProtection = 1

[expose:saved_tests]
pattern            = data/saved_tests
methods            = get,post,put,delete
skipCSRFProtection = 1
